In [ ]:
import numpy as np
import pandas as pd

In [7]:
data = np.array([
    ['Blue',  [1, 2],  1.1],
    ['Red',   [3, 4],  2.2],
    ['Pink',  [5, 6],  3.3],
    ['Grey',  [7, 8],  4.4],
    ['Black', [9, 10], 5.5],
], dtype=object)

data

array([['Blue', list([1, 2]), 1.1],
       ['Red', list([3, 4]), 2.2],
       ['Pink', list([5, 6]), 3.3],
       ['Grey', list([7, 8]), 4.4],
       ['Black', list([9, 10]), 5.5]], dtype=object)

In [9]:
df1 = pd.DataFrame(
    data,
    index=[1, 3, 5, 7, 9],
    columns=['color', 'list', 'number']
)

df1

   color     list number
1   Blue   [1, 2]    1.1
3    Red   [3, 4]    2.2
5   Pink   [5, 6]    3.3
7   Grey   [7, 8]    4.4
9  Black  [9, 10]    5.5

In [10]:
color_col  = pd.Series(['Blue', 'Red', 'Pink', 'Grey', 'Black'], index=[1,3,5,7,9])
list_col   = pd.Series([[1,2], [3,4], [5,6], [7,8], [9,10]],    index=[1,3,5,7,9])
number_col = pd.Series([1.1, 2.2, 3.3, 4.4, 5.5],               index=[1,3,5,7,9])

In [12]:
df2 = pd.DataFrame({
    'color':  color_col,
    'list':   list_col,
    'number': number_col
})

df2

   color     list  number
1   Blue   [1, 2]     1.1
3    Red   [3, 4]     2.2
5   Pink   [5, 6]     3.3
7   Grey   [7, 8]     4.4
9  Black  [9, 10]     5.5

In [14]:
print(df2.dtypes)

color         str
list       object
number    float64
dtype: object

In [15]:
for col in df2.columns:
    first_value = df2[col].iloc[0]
    print(f"{col}: column type = {df2[col].dtype}, value type = {type(first_value)}")

color: column type = str, value type = <class 'str'>
list: column type = object, value type = <class 'list'>
number: column type = float64, value type = <class 'numpy.float64'>