In [35]:
import pandas as pd
import numpy as np

df = pd.read_csv('data/iris.csv')
df.head()

  sepal_length sepal_width petal_length petal_width       flower
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0        -3.6         -1.4         0.2  Iris-setosa

In [36]:
df = df.drop(columns=['flower'])
df.head()

  sepal_length sepal_width petal_length petal_width
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0        -3.6         -1.4         0.2

In [37]:
for col in df.columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
dtype: object

In [38]:
df.isnull().sum()

sepal_length     4
sepal_width      9
petal_length    30
petal_width      3
dtype: int64

In [41]:


df['sepal_length'] = df['sepal_length'].fillna(df['sepal_length'].mean())
# mdedian is less effected by extraim
df['sepal_width']  = df['sepal_width'].fillna(df['sepal_width'].median())
df['petal_length'] = df['petal_length'].fillna(0)
df['petal_width']  = df['petal_width'].fillna(0)
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
dtype: int64

In [42]:
# Reload fresh data first so we have missing values again
df2 = pd.read_csv('data/iris.csv')
df2 = df2.drop(columns=['flower'])
for col in df2.columns:
    df2[col] = pd.to_numeric(df2[col], errors='coerce')

# Now fill everything with median
df2 = df2.fillna(df2.median())
df2.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
dtype: int64

In [ ]:
#Filling with 0:
#If a flower has a missing petal_length, filling it with 0 tells every future algorithm "this flower has no petal." That's not true — the measurement is just unknown. You've invented a data point that will pull the mean down and distort any model trained on it.
#Filling with the mean:
#Less harmful, but still problematic. Imagine 29 missing petal_length values all get replaced with the same mean value. Now you have 29 identical data points that didn't exist. This artificially reduces the variance of the column — the data looks more "clustered" than it really is, which can mislead machine learning models into false confidence.

In [44]:
# Find the special row 
df2[df2['sepal_width'] < 0]

    sepal_length  sepal_width  petal_length  petal_width
4            5.0         -3.6          -1.4          0.2
25           5.0         -3.0           4.5          0.2